ekf_filter_node:
  ros__parameters:
    frequency: 50.0                 # 필터 계산 주기(Hz)
    publish_tf: true                # TF publish 여부
    two_d_mode: true                # 2D 모드 (Z, Roll, Pitch 무시)

    # 프레임 명칭
    map_frame: map                  
    odom_frame: odom                
    base_link_frame: base_footprint 
    world_frame: odom              

    # Wheel Odometry 입력
    odom0: /odom/unfiltered
    odom0_config:                   # [X, Y, Z, Roll, Pitch, Yaw, Vx, Vy, Vz, Vroll, Vpitch, Vyaw, Ax, Ay, Az]
      [ false, false, false,        # X, Y, Z
        false, false, false,        # Roll, Pitch, Yaw
        true,  true,  false,        # Vx, Vy, Vz
        false, false, true,         # Vroll, Vpitch, Vyaw
        false, false, false ]       # Ax, Ay, Az
    odom0_differential: false       

    # Camera Odometry 입력
    odom1: /odom/camera
    odom1_config:
      [ true,  true,  true,         # X, Y, Z
        true,  true,  true,         # Roll, Pitch, Yaw
        false, false, false,        # Vx, Vy, Vz
        false, false, false,        # Vroll, Vpitch, Vyaw
        false, false, false ]       # Ax, Ay, Az
    odom1_differential: false
    odom1_relative: true
    odom1_queue_size: 2

    # IMU 입력
    imu0: /imu/data
    imu0_config:
      [ false, false, false,        # X, Y, Z
        true,  true,  true,         # Roll, Pitch, Yaw
        false, false, false,        # Vx, Vy, Vz
        true,  true,  true,         # Vroll, Vpitch, Vyaw
        true,  true,  false ]       # Ax, Ay, Az
    imu0_differential: false
